Castle_Apartments/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from miscellaneous import views as misc_views

urlpatterns = [
    path('', include('miscellaneous.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('property/', include('realEstate.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

handler404 = misc_views.error_404
handler500 = misc_views.error_500

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

# my profile etc.
urlpatterns = [

    path('profile', views.profile, name='user-profile'),
    path('profile/edit', views.edit_profile, name='edit-profile'),
    path('seller/<int:user_id>', views.seller_profile, name='seller-profile'),
    path('login', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page='login'), name='logout'),
    path('register', views.register, name='register')
]

realEstate/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Address(models.Model):
    country = models.CharField(max_length=255)
    municipality = models.CharField(max_length=255, blank=True, null=True)  # State, provance, region.
    city = models.CharField(max_length=255)
    postCode = models.CharField(max_length=16)
    streetName = models.CharField(max_length=255)
    houseNumber = models.CharField(max_length=16)
    apartmentNumber = models.CharField(max_length=16, blank=True, null=True)

    def __str__(self):
        return ', '.join([self.streetName + ' ' + self.houseNumber,
                          ('apartment ' + self.apartmentNumber + ', ' if self.apartmentNumber else '') + self.postCode,
                          self.city,
                          (self.municipality + ', ' if self.municipality else '') + self.country])


class Attribute(models.Model):
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.description


class Property(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=2048, blank=True)
    type = models.CharField(max_length=255)
    price = models.FloatField()
    nrBedrooms = models.IntegerField()
    nrBathrooms = models.IntegerField()
    squareMeters = models.IntegerField()
    constructionYear = models.IntegerField()
    address = models.OneToOneField(Address, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    attributes = models.ManyToManyField(Attribute)
    dateCreated = models.DateTimeField(default=timezone.now)
    sold = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class PropertyImage(models.Model):
    image = models.CharField(max_length=1024)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)

user/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from realEstate.models import Property, Address
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=32, blank=True, null=True)
    # A better way to store images
    profileImage = models.ImageField(upload_to='profileImages/', blank=True, null=True)
    # profileImage = models.ImageField(upload_to='profileImages/', default='/media/profileImages/user.png', blank=True, null=True)

    def __str__(self):
        return self.user.username


class RecentlyViewed(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)


class Favorites(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class PaymentInfo(models.Model):
    cardNumber = models.CharField(max_length=16)
    cardName = models.CharField(max_length=255)
    cardCVC = models.IntegerField()
    cardExpiryMonth = models.IntegerField()
    cardExpiryYear = models.IntegerField()
    address = models.OneToOneField(Address, on_delete=models.CASCADE)

    def __str__(self):
        return '**** **** **** ' + self.cardNumber[-4:]


class Purchase(models.Model):
    SSN = models.CharField(max_length=32)
    userInfo = models.ForeignKey(User, on_delete=models.CASCADE)
    paymentInfo = models.OneToOneField(PaymentInfo, on_delete=models.CASCADE)
    property = models.OneToOneField(Property, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.id

user/forms/registration_form.py
from django.forms import ModelForm, widgets
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from user.models import Profile


class UserForm(UserCreationForm):
    prefix = 'user'

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        widgets = {
            'username': widgets.TextInput(attrs={'class': "form-control"}),
            'first_name': widgets.TextInput(attrs={'class': "form-control"}),
            'last_name': widgets.TextInput(attrs={'class': "form-control"}),
            'email': widgets.EmailInput(attrs={'class': "form-control"}),
            'password': widgets.PasswordInput(attrs={'class': "form-control"}),
            'password2': widgets.PasswordInput(attrs={'class': "form-control"}),
        }


class ProfileForm(ModelForm):
    prefix = 'profile'

    class Meta:
        model = Profile
        exclude = [ 'id', 'user' ]
        widgets = {
            'phone': widgets.TextInput(attrs={'class': "form-control", 'minlength': 7}),
            #'profileImage': widgets.FileInput(attrs={}),
        }

user/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, reverse
from django.db.models import Case, When

from realEstate.models import Property
from user.models import Profile, RecentlyViewed, Favorites, Purchase
from user.forms.registration_form import ProfileForm, UserForm
# Create your views here.


@login_required
def profile(request):
    # Get all recently viewed properties for the user logged in
    pks = [rec.property_id for rec in RecentlyViewed.objects.filter(user_id=request.user.id).order_by('-timestamp')]
    preserved = Case(*[When(pk=pk, then=pos) for pos, pk in enumerate(pks)])  # To hold the order by timestamp
    recently_viewed_properties = Property.objects.filter(pk__in=pks).order_by(preserved)[:10]

    # Get all favorites for the user logged in
    pks2 = [fav.property_id for fav in Favorites.objects.filter(user_id=request.user.id)]
    favorite_properties = Property.objects.filter(pk__in=pks2)

    context = {'listings': Property.objects.filter(seller=request.user).order_by('-dateCreated'),
               'recently_viewed': recently_viewed_properties,
               'favorites': favorite_properties,
               'purchased': Purchase.objects.filter(userInfo_id=request.user.id)}
    return render(request, 'user/profile.html', context)



def seller_profile(request, user_id):
    context = {'listings': Property.objects.filter(seller__pk=user_id).order_by('-dateCreated'),
               'seller': User.objects.get(pk=user_id)}
    return render(request, 'user/seller-profile.html', context)


@login_required
def edit_profile(request):
    profile_instance = Profile.objects.get(pk=request.user.pk)
    if request.method == 'POST':
        profile_form = ProfileForm(instance=profile_instance, data=request.POST, files=request.FILES)
        user_form = UserForm(instance=request.user, data=request.POST)
        if profile_form.is_valid() and user_form.is_valid():
            # Saving to the database:
            prof = profile_form.save(commit=False)
            prof.profileImage = (prof.profileImage if prof.profileImage else 'profileImages/user.png')
            prof.save()
            user_form.save()
            new_user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password1'],)
            login(request, new_user)
            return redirect('user-profile')
        else:
            # The user reenters invalid information.
            context = {'profile_form': profile_form, 'user_form': user_form}
            return render(request, 'user/edit-profile.html', context)
    else:
        # The page is initially loaded with blank a form.
        context = {'profile_form': ProfileForm(instance=profile_instance),
                   'user_form': UserForm(instance=request.user)}
        return render(request, 'user/edit-profile.html', context)


def register(request):
    if request.method == 'POST':
        profile_form = ProfileForm(data=request.POST, files=request.FILES)
        user_form = UserForm(data=request.POST)
        if profile_form.is_valid() and user_form.is_valid():
            # Saving to the database:
            prof = profile_form.save(commit=False)
            prof.profileImage = (prof.profileImage if prof.profileImage else 'profileImages/user.png')
            prof.user = user_form.save()
            prof.save()
            new_user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password1'],)
            login(request, new_user)
            return redirect(reverse('user-profile'))
        else:
            # The user reenters invalid information.
            context = {'profile_form': profile_form, 'user_form': user_form}
            return render(request, 'user/register.html', context)
    else:
        # The page is initially loaded with blank a form.
        context = {'profile_form': ProfileForm(), 'user_form': UserForm()}
        return render(request, 'user/register.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return HttpResponse("Hello from the index function within the user app")

def profile(request):
    return  HttpResponse("This will be a profile page")

templates/user/edit-profile.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/css/editProfile.css">

    <div id="edit-profile-container">
        <div>
            <div class="heading">
                <h2>Edit Profile</h2>
                <p>Please edit your information in the corresponding lines below</p>
            </div>
            <div class="card" id="edit-profile-card">
                <form class="form form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" class="btn btn-primary submit-button" id="update-profile-button" value="Update">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/css/login.css">

            <div id="sign-in-container">
                <h2>Sign in</h2>
                <div class="card">
                    <div class="card-body">
                        <form class="form form-horizontal", method="post">
                        {% csrf_token %}
                                {{ form.username.label_tag }}
                            <div class="form-group">
                                {{ form.username }}
                            </div>
                                {{ form.password.label_tag }}
                            <div class="form-group">
                                {{ form.password }}
                            </div>
                            <p>New to Castle Apartments? <a id="register-link" href="{% url 'register' %}">Register</a></p>
                            <input type="submit", class="btn btn-primary submit-button" id="login-button" value="Sign In" />
                        </form>
                    </div>
                </div>
            </div>

{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/css/profiles.css">

    <!-- Rows and cols used to display profile to the left and properties to the right -->
    <div class="row">
        <div  id="left-column">

            <!-- Card container for profile -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                        <div class="card">
                            <div class="card-horizontal">
                                <div class="img-square-wrapper" id="profile-img-square-wrapper">
                                    <img class="profile-image" src="/media/{{ user.profile.profileImage }}" alt="Profile Image">
                                </div>
                                <div class="card-body">
                                    <h4 class="card-title">{{ user.first_name }} {{ user.last_name }}</h4>
                                    <p class="card-text">
                                        Username: {{ user.username }} <br>
                                        Email: {{ user.email }}<br>
                                        Tel: {{ user.profile.phone }}</p>
                                    <!-- Button to edit profile -->
                                    <a href="{% url 'edit-profile' %}" class="block btn btn-primary" id="edit-profile-button">Edit Profile</a>
                                    <!-- Button to seller profile -->
                                    <a href="{% url 'seller-profile' user.id %}" class="block btn btn-primary" id="view-profile-button">View Profile</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Button to add property-->
            <div id="add-property-button">
                {% csrf_token %}
                <a href="{% url 'add-property' %}" class="block btn btn-primary">Add Property</a>
            </div>

            <!-- Active properties -->
            <div id="active-listings-header">
                <h4>Active Listings</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for property in listings %}
                        {% if not property.sold %}
                            {% include 'user/single-active-listing.html' with property=property own_profile=True %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Sold properties -->
            <div id="sold-listings-header">
                <h4>Sold Properties</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for property in listings %}
                        {% if property.sold %}
                            {% include 'user/single-sold-listing.html' with property=property %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Bought properties -->
            <div id="sold-listings-header">
                <h4>Purchased Properties</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for purchased in purchased %}
                        {% include 'user/single-purchased-listing.html' with purchased=purchased %}
                    {% endfor %}
                    </div>
                </div>
            </div>

        </div>

        <div id="right-column">
            <!-- Card for recently viewed properties -->
            <h4 id="recently-viewed-header">Recently Viewed</h4>
            <div class="col-12 mt-3" id="recently-viewed-list">
                {% for recently_viewed_property in recently_viewed %}
                    {% include 'user/single-recently-viewed.html' with recently_viewed_property=recently_viewed_property %}
                {% endfor %}
            </div>

            <!-- Card for favorite properties -->
            <h4 id="recently-viewed-header">Favorites</h4>
            <div class="col-12 mt-3" id="recently-viewed-list">
                {% for favorite in favorites %}
                    {% include 'user/single-favorite.html' with favorite=favorite %}
                {% endfor %}
            </div>

        </div>

    </div>

{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/css/register.css">

    <div class="container" id="register-container" >
        <div class="row justify-content-center">
            <div>
                <h2>Create an account</h2>
                <div class="card" >
                    <div class="card-body" id="register-card">
                        <p>Already have an account? <a id="sign-in-link" href="{% url 'login' %}">Sign in</a></p>
                        <form class="form form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                            {{ registration_form }}
                            {{ user_form.as_p }}
                            {{ profile_form.as_p }}
                            <input type="submit" class="btn btn-primary submit-button" id="sign-up-button" value="Sign up" />
                        </form>
                        <br>
                        <p>By creating an account you'll be able to buy, sell, favorite and see your recently viewed properties!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/seller-profile.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/css/profiles.css">

    <!-- Rows and cols used to display profile to the left and properties to the right -->
    <div class="row">
        <div  id="left-column">

            <!-- Card container for profile -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                        <div class="card">
                            <div class="card-horizontal">
                                <div class="img-square-wrapper" id="profile-img-square-wrapper">
                                    <img class="profile-image" src="/media/{{ seller.profile.profileImage }}" alt="Seller Profile Image">
                                </div>
                                <div class="card-body">
                                    <h4 class="card-title">{{ seller.first_name }} {{ seller.last_name }}'s profile</h4>
                                    <p class="card-text">
                                        <br>
                                        Email: {{ seller.email }}<br>
                                        Tel: {{ seller.profile.phone }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Active properties -->
            <div id="active-listings-header">
                <h4>Active Listings</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for property in listings %}
                        {% if not property.sold %}
                            {% include 'user/single-active-listing.html' with property=property own_profile=False %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Sold properties -->
            <div id="sold-listings-header">
                <h4>Sold Properties</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for property in listings %}
                        {% if property.sold %}
                            {% include 'user/single-sold-listing.html' with property=property %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/sellerProfile.html
{% extends 'base.html' %}

{% block content %}

    <link rel="stylesheet" type="text/css" href="/static/css/profiles.css">

    <!-- Rows and cols used to display profile to the left and properties to the right -->
    <div class="row">
        <div  id="left-column">

            <!-- Card container for profile -->
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                        <div class="card">
                            <div class="card-horizontal">
                                <div class="img-square-wrapper" id="profile-img-square-wrapper">
                                    <img class="profile-image" src="/media/{{ seller.profile.profileImage }}" alt="Card image cap">
                                </div>
                                <div class="card-body">
                                    <h4 class="card-title">{{ seller.first_name }} {{ seller.last_name }}'s profile</h4>
                                    <p class="card-text">
                                        Username: {{ seller.username }} <br>
                                        Email: {{ seller.email }}<br>
                                        Tel: {{ seller.profile.phone }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Active properties -->
            <div id="active-listings-header">
                <h4>Active Listings</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for property in properties %}
                        {% if not property.sold %}
                            {% include 'user/single_active_listing.html' with property=property own_profile=False %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>

            <!-- Sold properties -->
            <div id="sold-listings-header">
                <h4>Sold Properties</h4>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 mt-3">
                    {% for property in properties %}
                        {% if property.sold %}
                            {% include 'user/single_sold_listing.html' with property=property %}
                        {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/single-active-listing.html
<a href="{% url 'property-details' property.id %}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal">
            <div class="card-body">
                <h4 class="card-title">{{ property.name }}</h4>
                <p class="card-text">
                    Size: {{ property.squareMeters }}m<sup>2</sup>, {{ property.type }}, {{ property.nrBedrooms }} bedrooms, {{ property.nrBathrooms }} bathrooms <br>
                    Price: {{ property.price }} $</p>
                {% if own_profile %}
                    <!-- Button to edit property -->
                    <a href="{% url 'edit-property' property.id %}" class="block btn btn-primary" id="edit-property-button">Edit</a>
                {% endif %}
            </div>
        </div>
    </div>
</a>

templates/user/single-purchased-listing.html
<a href="/property/{{ purchased.property.id }}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal">
            <div class="card-body">
                <h4 class="card-title">{{ purchased.property.name }}</h4>
                <p class="card-text">
                    Size: {{ purchased.property.squareMeters }}m<sup>2</sup>, {{ purchased.property.type }}, {{ purchased.property.nrBedrooms }} bedrooms, {{ purchased.property.nrBathrooms }} bathrooms <br>
                    Price: {{ purchased.property.price }} $</p>
                <!-- Button to see receipt of purchase -->
                <a href="{% url 'purchase-receipt' purchased.id %}" class="block btn btn-primary" id="see-receipt-button">See Receipt</a>
            </div>
        </div>
    </div>
</a>

templates/user/single-recently-viewed.html
<a href="{% url 'property-details' recently_viewed_property.id %}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal small-card-property">
            <div class="img-square-wrapper small-card-img-wrapper" id="recently-viewed-square-wrapper">
                <img class="small-property-image" src="{{recently_viewed_property.propertyimage_set.first.image}}" alt="Property Image">
            </div>
            <div class="card-body" id="recently-viewed-property">
                <h4 class="card-title">{{ recently_viewed_property.name }}</h4>
                <p class="card-text">Size: {{ recently_viewed_property.squareMeters }}m<sup>2</sup>, {{ recently_viewed_property.type }} <br>
                Price: {{ recently_viewed_property.price }} $</p>
            </div>
        </div>
    </div>
</a>

templates/user/single-sold-listing.html
<a href="/property/{{ property.id }}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal">
            <div class="card-body">
                <h4 class="card-title">{{ property.name }}</h4>
                <p class="card-text">
                    Size: {{ property.squareMeters }}m<sup>2</sup>, {{ property.type }}, {{ property.nrBedrooms }} bedrooms, {{ property.nrBathrooms }} bathrooms <br>
                    Price: {{ property.price }} $</p>
            </div>
        </div>
    </div>
</a>

templates/user/single_active_listing.html
<a href="{% url 'property-details' property.id %}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal">
            <div class="card-body">
                <h4 class="card-title">{{ property.name }}</h4>
                <p class="card-text">
                    Size: {{ property.squareMeters }}m<sup>2</sup>, {{ property.type }}, {{ property.nrBedrooms }} bedrooms, {{ property.nrBathrooms }} bathrooms
                </p>
                <p class="card-subtitle mb-2">Price: {{ property.price }} $</p>
                {% if own_profile %}
                    <!-- Button to edit property -->
                    <a href="{% url 'edit_property' property.id %}" class="block btn btn-primary" id="edit-property-button">Edit</a>
                {% endif %}
            </div>
        </div>
    </div>
</a>

templates/user/single_purchased_listing.html
<a href="/property/{{ purchased.property.id }}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal">
            <div class="card-body">
                <h4 class="card-title">{{ purchased.property.name }}</h4>
                <p class="card-text">
                    Size: {{ purchased.property.squareMeters }}m<sup>2</sup>, {{ purchased.property.type }}, {{ purchased.property.nrBedrooms }} bedrooms, {{ purchased.property.nrBathrooms }} bathrooms <br>
                    Price: {{ purchased.property.price }} $</p>
                <!-- Button to see receipt of purchase -->
                <a href="{% url 'purchase_review' purchased.id %}" class="block btn btn-primary">See Receipt</a>
            </div>
        </div>
    </div>
</a>

templates/user/single_recently_viewed.html
<a href="{% url 'property-details' recently_viewed_property.id %}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal small-card-property">
            <div class="img-square-wrapper small-card-img-wrapper" id="recently-viewed-square-wrapper">
                <img class="small-property-image" src="{{recently_viewed_property.propertyimage_set.first.image}}">
            </div>
            <div class="card-body" id="recently-viewed-property">
                <h4 class="card-title">{{ recently_viewed_property.name }}</h4>
                <p class="card-text">Size: {{ recently_viewed_property.squareMeters }}m<sup>2</sup>, {{ recently_viewed_property.type }}</p>
                <p class="card-subtitle mb-2">Price: {{ recently_viewed_property.price }} $</p>
            </div>
        </div>
    </div>
</a>

templates/user/single_sold_listing.html
<a href="/property/{{ property.id }}" class="link-to-property">
    <div class="card">
        <div class="card-horizontal">

            <div class="card-body">
                <h4 class="card-title">{{ property.name }}</h4>
                <p class="card-text">
                    Size: {{ property.squareMeters }}m<sup>2</sup>, {{ property.type }}, {{ property.nrBedrooms }} bedrooms, {{ property.nrBathrooms }} bathrooms <br>
                    Price: {{ property.price }} $</p>
            </div>
        </div>
    </div>
</a>